version: '3'
services:
    shrty:
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: leeartem/shrty
        container_name: shrty-container
        ports:
            - '${APP_PORT:-80}:8000'
        environment:
            WWWUSER: '${WWWUSER}'
            # CHOKIDAR_USEPOLLING: true
        volumes:
            - '.:/var/www/html'
        networks:
            - api
        depends_on:
            - mongo
    mongo:
        image: 'mongo:4.4'
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
            MONGO_INITDB_DATABASE: '${DB_DATABASE}'
        volumes:
            - 'mongo:/data/db'
        networks:
            - api
networks:
    api:
        driver: bridge
volumes:
    mongo:
        driver: local
